In [5]:
import numpy as np

list_ = [ 1,2,3,4,5]

array_list = np.array(object = list_)

In [9]:
# 1.Ans.
"""
Yes, there is a difference in the data type of variables list_ and array_list in Python.

So, while list_ and array_list may contain the same values, their data types 
are different, with list_ being a built-in Python data type, and array_list being a NumPy array.
"""
type(list_), type(array_list)




(list, numpy.ndarray)

In [10]:
# 2.Ans.

list_ = [ 1,2,3,4,5]

array_list = np.array(object = list_)

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))
    

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [11]:
# 3.Ans.

# yes.

list_ = [ 1,2,3,4,5]
array_list = np.array(object = list_, dtype = int)

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [16]:
# 4.Ans.

num_array.shape, num_array.size

((2, 3), 6)

In [25]:
# 5.Ans.

import numpy as np

array = np.zeros((3,3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
array.shape, array.size

((3, 3), 9)

In [29]:
# 6.Ans.

import numpy as np
num = np.identity(5)
print(num)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
